version: '3.8'

services:
  # TiDB Database
  tidb:
    image: pingcap/tidb:latest
    ports:
      - "4000:4000"
    command:
      - --store=mocktikv
      - --advertise-address=tidb
      - --log.level=info

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Auth Service
  auth:
    build:
      context: .
      dockerfile: backend/services/auth/Dockerfile
    ports:
      - "8081:8080"
      - "9091:9090"
    environment:
      - SERVICE_NAME=auth-service
      - PORT=8080
      - METRICS_PORT=9090
      - DATABASE_DSN=root@tcp(tidb:4000)/eggybyte?charset=utf8mb4&parseTime=True
      - LOG_LEVEL=info
    depends_on:
      - tidb
      - redis

  # User Service
  user:
    build:
      context: .
      dockerfile: backend/services/user/Dockerfile
    ports:
      - "8082:8080"
      - "9092:9090"
    environment:
      - SERVICE_NAME=user-service
      - PORT=8080
      - METRICS_PORT=9090
      - DATABASE_DSN=root@tcp(tidb:4000)/eggybyte?charset=utf8mb4&parseTime=True
      - LOG_LEVEL=info
    depends_on:
      - tidb
      - redis
