# EggyByte Core Configuration Template
# Copy this file to your project and customize as needed

# Service Configuration
service:
  name: "my-service"
  version: "1.0.0"
  environment: "development" # development, staging, production

# Server Configuration
server:
  port: 8080
  metrics_port: 9090
  health_port: 8081
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

# Logging Configuration
logging:
  level: "info" # debug, info, warn, error, fatal
  format: "json" # json, console
  output: "stdout" # stdout, stderr, file
  file_path: "/var/log/service.log"
  max_size: 100 # MB
  max_age: 7 # days
  max_backups: 3
  compress: true

# Database Configuration
database:
  driver: "mysql" # mysql, postgres, sqlite
  dsn: "user:password@tcp(localhost:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: "1h"
  conn_max_idle_time: "30m"

# Redis Configuration (Optional)
redis:
  enabled: false
  addr: "localhost:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_conn_age: "1h"
  pool_timeout: "4s"
  idle_timeout: "5m"
  idle_check_frequency: "1m"

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_path: "/metrics"
  health_path: "/health"
  liveness_path: "/livez"
  readiness_path: "/readyz"
  prometheus_enabled: true

# Kubernetes Configuration (Optional)
kubernetes:
  enabled: false
  namespace: "default"
  configmap_name: "service-config"
  secret_name: "service-secrets"
  watch_config: true
  watch_interval: "30s"

# Security Configuration
security:
  tls:
    enabled: false
    cert_file: "/etc/ssl/certs/service.crt"
    key_file: "/etc/ssl/private/service.key"
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    max_age: 86400

# Rate Limiting (Optional)
rate_limit:
  enabled: false
  requests_per_minute: 100
  burst_size: 20

# Circuit Breaker (Optional)
circuit_breaker:
  enabled: false
  failure_threshold: 5
  timeout: "30s"
  max_requests: 3
  interval: "1m"
