# Kubernetes Deployment for EggyByte Core applications
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eggybyte-service
  namespace: eggybyte-system
  labels:
    app: eggybyte-service
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eggybyte-service
  template:
    metadata:
      labels:
        app: eggybyte-service
        version: v1.0.0
    spec:
      serviceAccountName: eggybyte-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: eggybyte-service
        image: eggybyte/service:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        env:
        - name: SERVICE_NAME
          value: "eggybyte-service"
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "json"
        envFrom:
        - configMapRef:
            name: eggybyte-service-config
        - secretRef:
            name: eggybyte-service-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /livez
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: eggybyte-service
  namespace: eggybyte-system
  labels:
    app: eggybyte-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: health
  selector:
    app: eggybyte-service

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eggybyte-service-config
  namespace: eggybyte-system
data:
  DATABASE_MAX_OPEN_CONNS: "100"
  DATABASE_MAX_IDLE_CONNS: "10"
  DATABASE_CONN_MAX_LIFETIME: "1h"
  REDIS_POOL_SIZE: "10"
  REDIS_MIN_IDLE_CONNS: "5"
  MONITORING_ENABLED: "true"
  PROMETHEUS_ENABLED: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: eggybyte-service-secrets
  namespace: eggybyte-system
type: Opaque
data:
  DATABASE_DSN: # base64 encoded database connection string
  REDIS_PASSWORD: # base64 encoded redis password
  JWT_SECRET: # base64 encoded JWT secret

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eggybyte-service
  namespace: eggybyte-system
